### ISSUE TITLE
Incorrect address results in server error

### ISSUE THREAD

**Issue by thevirtuoso1973** [toms3t/Propalyzer#101]
If I search for 'San Francisco' or 'New York' a server error is thrown - could add some more error handling for inputs, to avoid a server error 500. 
Could also provide the expected input format on the front page (US address format).

**Comment by Nitsujed** [comment]
@thevirtuoso1973 Thank you for finding that. You are correct, we need to improve the address string validation after the user inputs "something". Some inputs do cause the proper redirect like "San Francisco, CA" to our input format page, but we can do a better job in validation.

We also havent done much in the way of "styling" the site, just been focusing on functionality. I think a good run through of usability would be helpful and adding some "hints" like you suggest would be a good addition.

Thanks again for your suggestions!

**Comment by toms3t** [comment]
Added some logic in greatschools.py to check for the 200 response from the API. If no 200, then we default the schools to "unknown". Thanks @thevirtuoso1973 for the bug report! Agree that we need to improve address validation.
