### ISSUE TITLE
Find assigned schools and school scores for a given address

### ISSUE THREAD

**Issue by toms3t** [toms3t/Propalyzer#16]
greatschools.org has an API....

**Comment by Nitsujed** [comment]
@toms3t I'm going to work on adding this feature. Do you have certain parameters you would like to see brought in? I'm not sure what your ultimate end game is with this program so just want to make sure I am adding the necessary data you require.

**Comment by toms3t** [comment]
@Nitsujed I figured we just need the assigned schools (elementary, middle, high) and school scores should suffice. My goal with this app is to provide investors with all relevant information to help the investor analyze the return (cash flow and appreciation) of a rental property.

**Comment by Nitsujed** [comment]
@toms3t Just an update, still waiting for my API approval. They review each case and have some strict requirements, been some back and forth with their approval dept so far. So you may want to put your application in now as well.

Here is a little snippet of some of the stuff they require, "Please note, our freemium API has a few notable terms which include display of our school data on a free and public website (without registration, sign up, or login), deep linking back to GreatSchools, and our 3,000 daily call limit."

**Comment by Nitsujed** [comment]
Finally got the approval, but on a 3month trial period. They would like to see our site after that period to ensure we are complying with their terms. Are you planning to apply for a key also? I'm going to start working on this and put a hook in that if there is no api key provided in secret then leave fields blank.

**Comment by toms3t** [comment]
Yeah, I'll apply for a key. We'll need to figure out how to implement a CAPTCHA or another way to keep out bots.

**Comment by Nitsujed** [comment]
@toms3t So the response from the API call gives us a list of all schools within a specified radius of the address, not necessarily the school the property is zoned for. For instance, I did a call with my home address with a 5 mile radius for elementary schools and got about 8 schools. Filtered out the schools in nearby counties (which will be easy to do with the info we should have on hand) and reduced it to 3. My kids elem school was the furthest in that list, about 4.5 miles away, not really sure why my kids don't go to the other two in the list that are closer... I imagine middle schools would be fewer and high fewer still (my kids was top of both lists), but we may have to make some business decisions on which to display to the user. I was thinking for property buying purposes it wouldn't hurt to know what the local schools in general are scoring so maybe stick to top 3 of each level returned? within 5 miles, 10 miles? If only one school within 10 miles, then easy chose? What if its rural and the nearest school is 15 miles, hope the buyer isn't interested in schools? Just public or add charter and private?

Here is that call that I'm using [GreatSchools Nearby](https://www.greatschools.org/api/docs/nearby-schools/)

What are your thoughts?

**Comment by Nitsujed** [comment]
@toms3t Created branch greatschools and pulled in my changes. There is still some work needed in this branch to add the data to the UI however you see fit. I put details in the pull request on how it serves the data, but if you have any questions, hit me up.

**Comment by toms3t** [comment]
@Nitsujed I realized I didn't answer your post from Nov 13. I think having the elementary, middle and high schools work, both public and private. Even if we don't get the exact assigned schools, having nearby school info and their ratings will suffice. I'll check out the new branch. Thanks!

**Comment by Nitsujed** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [A user would like to know what the local schools are and what are their grades](https://trello.com/c/xFrLwDe5/3-a-user-would-like-to-know-what-the-local-schools-are-and-what-are-their-grades)

**Comment by toms3t** [comment]
@Nitsujed - pull request ready for review.

**Comment by toms3t** [comment]
Feature pushed to master on 2/6.
