### ISSUE TITLE
Better overall theme for the site?

### ISSUE THREAD

**Issue by toms3t** [toms3t/Propalyzer#18]
The current theme is fairly basic. Let's make it look more professional.

**Comment by Nitsujed** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Redesign website to have a better overall theme](https://trello.com/c/vj3KBI6K/2-redesign-website-to-have-a-better-overall-theme)

**Comment by nikauhrinova** [comment]
Hi, I'd like to work on this, is it still open?

**Comment by toms3t** [comment]
@nikauhrinova - it is! Would love to see a better theme to the site.

**Comment by toms3t** [comment]
@nikauhrinova - thanks for the great theme! It's in prod now.
