### ISSUE TITLE
Incorporate crime scoring of an area

### ISSUE THREAD

**Issue by toms3t** [toms3t/Propalyzer#29]
Need an API or way to get a crime score for an address given.

**Comment by Nitish18** [comment]
hi @toms3t , looks good  i am working on it.
one thing, should I use another API for crime rate or zillow provide that API also ??

**Comment by toms3t** [comment]
From what I've seen, Zillow does not provide crime data. We'll need a different API.

**Comment by toms3t** [comment]
Found a crime score by address through areavibes.com
