### ISSUE TITLE
BUG: Addresses with multiple names throw error

### ISSUE THREAD

**Issue by toms3t** [toms3t/Propalyzer#41]
Test: 4395 E Kit Fox Ln, Post Falls, ID 83854

**Comment by suprithcs** [comment]
Hi @toms3t, I'm new to the code base. A quick grep for "address" on repo listed many candidates. However, I felt changes are required at only zillow_api.py and views.py files. Could you please provide more information?

**Comment by toms3t** [comment]
@suprithIUB Most of the logic now resides in the set_zillow_url method in the Zillow_api.py file. We've improved the logic now to include more variations of address types but I'm sure there are some that we haven't accounted for. Feel free to test multiple types of addresses and let me know what you find.
