### ISSUE TITLE
Addresses that are missing fields in Zillow throw errors

### ISSUE THREAD

**Issue by Nitsujed** [toms3t/Propalyzer#43]
While setting this up, I tested an address that happened to not have curr_value, value_low, or value_high and was throwing IndexErrors. I added try/excepts to them to prevent this, but it seems there needs to be better handling added for fields that are not in Zillow for certain addresses

**Comment by toms3t** [comment]
Good catch - I'll add in exception handling for those cases.

**Comment by Nitsujed** [comment]
I'd like to work this and change the way you are parsing your xml response. Do you mind if I check out a branch and make some big changes with this section of code? You can decide if you like it or not.

Also, I like the concept you are trying to do here, if youd like, I'd love to partner with you and work on this project together.

**Comment by toms3t** [comment]
Absolutely! Let’s collaborate - there’s a lot we can do with this concept.

Feel free to re-factor the XML parsing piece. I played around with the ‘xmltodict’ module but didn’t like the way it parsed the XML. I just decided to use regex as I found it to be the quickest way to get the data.

I’m just about to push a new feature which involves scoring the area of the address based on several factors.

**Comment by toms3t** [comment]
@Nitsujed - any luck re-factoring the XML parsing section?

**Comment by Nitsujed** [comment]
@toms3t I got some ideas in the works I've been doing offline. I just merged your changes into my repo so I capture the changes you've made and will start applying my new changes and send the pull request. Hopefully get something by the end of the weekend to you.
