### ISSUE TITLE
Create a test case for address parsing and zillow api calls

### ISSUE THREAD

**Issue by Nitsujed** [toms3t/Propalyzer#51]
Need to write a test case that takes a list of a dozen or so addresses that test various permutations of US addresses and run it through the `def address(request)` method to ensure good coverage of possible address inputs don't break the function.

This could probably be written in a way that it exercises the method without having to stand up a Django server. 

This may have to wait until issue #43 is resolved.

**Comment by toms3t** [comment]
@Nitsujed - added "test_zillowapi.py" file with test cases for zillow API calls using 10 US addresses (various formats).
