### ISSUE TITLE
Find source/API for property taxes

### ISSUE THREAD

**Issue by toms3t** [toms3t/Propalyzer#6]
Need a reliable API for obtaining property tax information for a given address.

**Comment by Nitsujed** [comment]
@toms3t Do you know of any sites that do this? All my searches came up with either individual county appraisers or paid sites that claim they have over 150 million property records but you have to pay $.10 per API call.

Zillow has the last assessed value and year, but I realize that doesn't mean much to the end-user in regards to how much was actually paid to the county tax.

**Comment by toms3t** [comment]
@Nitsujed - this one has been a challenge. I found [this](https://rets.ly/docs/retsly/) service that provides an API and I was able to get an invite to use it. I'm exploring the API now to see if we can get property tax data.
