### ISSUE TITLE
Create prerequisites and installation info in readme for Windows users

### ISSUE THREAD

**Issue by toms3t** [toms3t/Propalyzer#8]

**Comment by ccheng26** [comment]
Is this issue being worked on?

**Comment by toms3t** [comment]
Nope, do you want to tackle it? ;)


On Oct 5, 2017, at 4:55 PM, Connie Cheng <notifications@github.com<mailto:notifications@github.com>> wrote:


Is this issue being worked on?

**Comment by aruru99** [comment]
I'm confused... The current README.md file seems pretty extensive; what part of the installation/prerequisites isn't compatible for windows users in particular?

**Comment by toms3t** [comment]
I just haven’t converted the instructions to Windows yet - I think it’s fairly similar but I haven’t checked.


On Oct 5, 2017, at 4:59 PM, Andrew Kim <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm confused... The current README.md file seems pretty extensive; what part of the installation/prerequisites isn't compatible for windows users in particular?

**Comment by aruru99** [comment]
I'll work on this in 30 minutes; have to do homework real quick. Cheers!

**Comment by ccheng26** [comment]
Up for working on this if any additional help is needed. Mostly familiar with powershell.

**Comment by aruru99** [comment]
Is it okay if instead of downloading python and installing virtualenv, I direct users to install miniconda?

**Comment by toms3t** [comment]
Sure - however they choose to create their isolated environment is cool with me. Maybe we suggest using Pipenv as well?


On Oct 5, 2017, at 5:46 PM, Andrew Kim <notifications@github.com<mailto:notifications@github.com>> wrote:


Is it okay if instead of downloading python and installing virtualenv, I direct users to install miniconda?

**Comment by aruru99** [comment]
Made the pull request.
I didn't do that much work, but I still learned a lot and had fun with it.
Thanks!

**Comment by aruru99** [comment]
Cool app btw :^)

**Comment by toms3t** [comment]
Thanks Andrew! Let me know if you have any ideas for feature requests. There’s a lot that can be done here.


On Oct 5, 2017, at 6:19 PM, Andrew Kim <notifications@github.com<mailto:notifications@github.com>> wrote:


Cool app btw :^)
