### ISSUE TITLE
Find API for natural disaster info by address

### ISSUE THREAD

**Issue by toms3t** [toms3t/Propalyzer#9]
Good for understanding insurance needs for a new investment opportunity

**Comment by mohit-0212** [comment]
Hey, so what exactly do you need?

**Comment by toms3t** [comment]
Hey Mohit!

Looking for a way to correlate regional natural disasters (earthquake, hurricanes, etc.) to an address so that we can display that information in the app. There’s a site called homefacts.com <http://homefacts.com/> (just plug in an address) that provides that info but I don’t think they have an API. 


-Tom

**Comment by mohit-0212** [comment]
So I checked the website, it doesn't provide much info on the natural disasters. If it does, maybe we can try and scrape it, if it is allowed.
I saw this https://reliefweb.int/help/api. Haven't used it personally, might turn out to be helpful.

**Comment by toms3t** [comment]
Homefacts doesn't allow scraping per their terms of use, unfortunately. That reliefweb API might work...

**Comment by mohit-0212** [comment]
What should I do ?

**Comment by toms3t** [comment]
Just added a few more issues. Feel free to pick any of them to work on!

**Comment by bipinkumar919** [comment]
https://earthquake.usgs.gov/fdsnws/event/1/ they have api for earthquakes . I have used it. Try it.

**Comment by Nitsujed** [comment]
@toms3t I think [FEMA Disaster Declaration API](https://www.fema.gov/openfema-dataset-disaster-declarations-summaries-v1) will be our best bet here. It can filter by state and county, which I think is refined enough for a potential buyer and we should be getting from the Zillow API. Based on what it provides, I would suggest we present the user with an aggregate of the amount of times a specific disaster occurred for that county. Ex. Hurricanes -2, Tornadoes -4, etc. I feel like the date of the incidents would be beneficial too, but based on the area and frequency of occurrences, this could become a very long list. Maybe expand it to be Hurricanes -2 (dates of occurrences), Tornadoes -3 (dates), etc.

Here is an example of the fields returned, check the website for more details of each field:

`"disasterNumber": 214,
      "ihProgramDeclared": false,
      "iaProgramDeclared": true,
      "paProgramDeclared": true,
      "hmProgramDeclared": false,
      "state": "GA",
      "declarationDate": "1966-03-14T04:00:00.000Z",
      "disasterType": "DR",
      "incidentType": "Flood",
      "title": "FLOODING",
      "incidentBeginDate": "1966-03-14T04:00:00.000Z",
      "incidentEndDate": "1966-03-14T04:00:00.000Z",
      "declaredCountyArea": "Paulding (County)",
      "hash": "35e0c62ee24166b1532949c2a477e2cb",
      "lastRefresh": "2017-08-09T13:49:37.980Z",
      "disasterCloseOutDate": "1967-08-24T04:00:00.000Z",
      "placeCode": 99223,
      "id": "5465a01149d3d6a93c732e44"`

**Comment by Nitsujed** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Todo](https://trello.com/c/iIjz1Ygn/1-todo)

**Comment by Nitsujed** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add the ability to show disaster statistics for an address](https://trello.com/c/89NZpk2K/1-add-the-ability-to-show-disaster-statistics-for-an-address)

**Comment by mohit741** [comment]
This issue is still open. Can I do something? I'm new to open source contributions. @toms3t

**Comment by toms3t** [comment]
@mohit741 - I've added disaster information in the latest merge. I invite you to pull down the master branch and run it locally on your machine to test the additional disaster info. Let me know what you think. For now, I'm going to close this issue but feel free to tackle any of the other issues. How about [this](https://github.com/toms3t/Propalyzer/issues/90) issue?
